spring:
  h2:
    console.enabled: true
    console.path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false